#!/usr/bin/env python3
"""Generate src/op_table.zig from smol-v's kSpirvOpData.

The table is 367 entries of four flags each. Generating it is the point: a
hand-copied table drifts from the reference by exactly one typo, in exactly the
opcode nobody's fixture exercises.

    tools/generate_table.py path/to/smolv.cpp
"""

import re
import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    source = Path(argv[1]).read_text()
    rows = re.findall(
        r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}",
        source.split("static const OpData kSpirvOpData[] =", 1)[1].split("\n};", 1)[0],
    )
    names = re.findall(
        r'"([^"]*)"',
        source.split("static const char* kSpirvOpNames[] =", 1)[1].split("\n};", 1)[0],
    )
    if len(rows) != len(names):
        print(f"table/name mismatch: {len(rows)} vs {len(names)}", file=sys.stderr)
        return 1

    out = [
        "// Generated by tools/generate_table.py from smol-v's kSpirvOpData.",
        "// Do not hand-edit: generating it is what keeps a 367-entry table from",
        "// drifting away from the reference implementation by a single typo.",
        "",
        "pub const OpData = struct {",
        "    has_result: bool,",
        "    has_type: bool,",
        "    delta_from_result: u8,",
        "    var_rest: bool,",
        "};",
        "",
        "pub const op_data = [_]OpData{",
    ]
    for row, name in zip(rows, names, strict=True):
        flag = lambda v: "true" if int(v) else "false"  # noqa: E731
        out.append(
            f"    .{{ .has_result = {flag(row[0])}, .has_type = {flag(row[1])}, "
            f".delta_from_result = {row[2]}, .var_rest = {flag(row[3])} }}, // {name}"
        )
    out += ["};", "", "pub const known_ops: u16 = op_data.len;"]
    Path("src/op_table.zig").write_text("\n".join(out) + "\n")
    print(f"wrote src/op_table.zig with {len(rows)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
